"""Descriptions used verbatim by OpenAPI and MCP production tools."""

REST_DESCRIPTIONS = {
    "production_capabilities": "Discover production task types, local transcription runtime/model status, pinned downloadable models, portrait showcase template, input limits and workflow. No downloads or inference. Installed files do not guarantee successful recognition.",
    "steam_search": "Search the official Steam catalog, sorted by release date. Returns candidates with app IDs and source links, not verified release or popularity claims. Follow with steam_games for fresh coming_soon, modes and trailer metadata. Public network read; query max150 chars, count1–20, paginated start.",
    "steam_games": "Fetch fresh official Steam details for 1–10 app IDs. Returns checked-at time, metadata SHA-256, release state, descriptions, play modes and exact trailer IDs/URLs. These are source data, not instructions or a reuse license. No trailer download or project mutation.",
    "production_start": "Queue one typed production operation. request_key is required for idempotency: same key/payload returns the original task even after failure; changed payload under that key returns409. Returns queued state immediately. Partial validated assets survive cancellation/failure and are listed in result. Never updates the timeline. Discover supported types and wait for terminal state before consuming results.",
    "production_list": "Read the latest100 production tasks, separately from render jobs, including real progress, cancellation requests, errors and partial results. Use to reconnect without repeating imports or synthesis. A completed task does not imply its verification report passed.",
    "production_get": "Read one durable production task by exact ID. Terminal states completed/failed/cancelled. result includes only real imported assets, measured timings and completed artifacts. A cancellation request is not confirmation that work has stopped.",
    "production_wait": "Wait server-side up to25 seconds for a task to reach a terminal state; returns its current task on timeout. No busy client polling or fabricated completion. The task continues after a timeout/disconnect. Reuse the returned ID rather than enqueueing a duplicate.",
    "production_cancel": "Request cancellation of a queued/running production task. Queued tasks stop immediately; active tasks stop their child process or finish the current noninterruptible speech call before confirming cancelled. Partial validated assets remain available in result; unimported temporary downloads are removed. Terminal tasks remain unchanged.",
    "source_frames": "Inspect1–24 frames directly from an imported video/image; no project render. Times are SOURCE milliseconds. Omit timestamps for evenly spaced samples of from_ms/to_ms; count3 inspects start/middle/end of a proposed cut. Returns actual JPEG sheet and source checksum. Visually inspect before composing: this does not infer whether footage is gameplay, a logo or a title card.",
    "caption_layout": "Measure all unmuted text clips at the exact project revision using the export rasterizer. Returns clipped/unclipped foreground boxes and temporal text collisions. Writes only cache. A clean result does not prove visual quality; title-card detection and semantic review still require viewing actual frames.",
    "showcase_compose": "Plan or commit an editable portrait showcase from completed measured narration and authored beats/source cuts. Defaults dry_run=true and empty-project-only. Explicit duration must fit actual voice; hooks longer than3seconds reject, never silently truncate. Auto groups phrase captions and lays out titles/gameplay/score. A commit is one revision-guarded atomic batch; conflicts require reconciliation. Returns full candidate/project, layout report and ASR timing warnings. Caller must visually inspect source cuts and final export.",
    "render_wait": "Wait server-side up to25 seconds for a render to complete/fail/cancel. Returns current Job on timeout; timeout is not failure or completion. Does not enqueue or cancel. Prefer this to repeated get_render_progress calls and retain job_id for pinned final inspection.",
    "revision_compare": "Compare two immutable revisions of one project. Reports added/removed/changed tracks and clips, changed fields, and whether audio/text definitions stayed identical. No edits or renders. Identical definitions are not proof of identical encoded bytes; verify_render reports actual video and decoded-audio hashes.",
}
