/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as RedocRouteImport } from './routes/redoc'
import { Route as WorkspaceLibraryRouteImport } from './routes/_workspace.library'
import { Route as WorkspaceRendersRouteImport } from './routes/_workspace.renders'
import { Route as WorkspaceSettingsRouteImport } from './routes/_workspace.settings'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as DocsOauth2RedirectRouteImport } from './routes/docs.oauth2-redirect'
import { Route as McpSplatRouteImport } from './routes/mcp.$'
import { Route as MediaSplatRouteImport } from './routes/media.$'
import { Route as WorkspaceChannelsIndexRouteImport } from './routes/_workspace.channels.index'
import { Route as WorkspaceChannelsChannelIdRouteImport } from './routes/_workspace.channels.$channelId'
import { Route as WorkspaceProjectsIndexRouteImport } from './routes/_workspace.projects.index'
import { Route as WorkspaceProjectsProjectIdRouteImport } from './routes/_workspace.projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const RedocRoute = RedocRouteImport.update({
  id: '/redoc',
  path: '/redoc',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceLibraryRoute = WorkspaceLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceRendersRoute = WorkspaceRendersRouteImport.update({
  id: '/renders',
  path: '/renders',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsOauth2RedirectRoute = DocsOauth2RedirectRouteImport.update({
  id: '/docs/oauth2-redirect',
  path: '/docs/oauth2-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const McpSplatRoute = McpSplatRouteImport.update({
  id: '/mcp/$',
  path: '/mcp/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSplatRoute = MediaSplatRouteImport.update({
  id: '/media/$',
  path: '/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceChannelsIndexRoute = WorkspaceChannelsIndexRouteImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceChannelsChannelIdRoute =
  WorkspaceChannelsChannelIdRouteImport.update({
    id: '/channels/$channelId',
    path: '/channels/$channelId',
    getParentRoute: () => WorkspaceRoute,
  } as any)
const WorkspaceProjectsIndexRoute = WorkspaceProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceProjectsProjectIdRoute =
  WorkspaceProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redoc': typeof RedocRoute
  '/library': typeof WorkspaceLibraryRoute
  '/renders': typeof WorkspaceRendersRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/oauth2-redirect': typeof DocsOauth2RedirectRoute
  '/mcp/$': typeof McpSplatRoute
  '/media/$': typeof MediaSplatRoute
  '/channels/$channelId': typeof WorkspaceChannelsChannelIdRoute
  '/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
  '/channels/': typeof WorkspaceChannelsIndexRoute
  '/projects/': typeof WorkspaceProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redoc': typeof RedocRoute
  '/library': typeof WorkspaceLibraryRoute
  '/renders': typeof WorkspaceRendersRoute
  '/settings': typeof WorkspaceSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/oauth2-redirect': typeof DocsOauth2RedirectRoute
  '/mcp/$': typeof McpSplatRoute
  '/media/$': typeof MediaSplatRoute
  '/channels/$channelId': typeof WorkspaceChannelsChannelIdRoute
  '/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
  '/channels': typeof WorkspaceChannelsIndexRoute
  '/projects': typeof WorkspaceProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/redoc': typeof RedocRoute
  '/_workspace/library': typeof WorkspaceLibraryRoute
  '/_workspace/renders': typeof WorkspaceRendersRoute
  '/_workspace/settings': typeof WorkspaceSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/docs/oauth2-redirect': typeof DocsOauth2RedirectRoute
  '/mcp/$': typeof McpSplatRoute
  '/media/$': typeof MediaSplatRoute
  '/_workspace/channels/$channelId': typeof WorkspaceChannelsChannelIdRoute
  '/_workspace/projects/$projectId': typeof WorkspaceProjectsProjectIdRoute
  '/_workspace/channels/': typeof WorkspaceChannelsIndexRoute
  '/_workspace/projects/': typeof WorkspaceProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/redoc'
    | '/library'
    | '/renders'
    | '/settings'
    | '/api/$'
    | '/docs/oauth2-redirect'
    | '/mcp/$'
    | '/media/$'
    | '/channels/$channelId'
    | '/projects/$projectId'
    | '/channels/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/redoc'
    | '/library'
    | '/renders'
    | '/settings'
    | '/api/$'
    | '/docs/oauth2-redirect'
    | '/mcp/$'
    | '/media/$'
    | '/channels/$channelId'
    | '/projects/$projectId'
    | '/channels'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/redoc'
    | '/_workspace/library'
    | '/_workspace/renders'
    | '/_workspace/settings'
    | '/api/$'
    | '/docs/oauth2-redirect'
    | '/mcp/$'
    | '/media/$'
    | '/_workspace/channels/$channelId'
    | '/_workspace/projects/$projectId'
    | '/_workspace/channels/'
    | '/_workspace/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  RedocRoute: typeof RedocRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DocsOauth2RedirectRoute: typeof DocsOauth2RedirectRoute
  McpSplatRoute: typeof McpSplatRoute
  MediaSplatRoute: typeof MediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redoc': {
      id: '/redoc'
      path: '/redoc'
      fullPath: '/redoc'
      preLoaderRoute: typeof RedocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/library': {
      id: '/_workspace/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof WorkspaceLibraryRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/renders': {
      id: '/_workspace/renders'
      path: '/renders'
      fullPath: '/renders'
      preLoaderRoute: typeof WorkspaceRendersRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/settings': {
      id: '/_workspace/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/oauth2-redirect': {
      id: '/docs/oauth2-redirect'
      path: '/docs/oauth2-redirect'
      fullPath: '/docs/oauth2-redirect'
      preLoaderRoute: typeof DocsOauth2RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp/$': {
      id: '/mcp/$'
      path: '/mcp/$'
      fullPath: '/mcp/$'
      preLoaderRoute: typeof McpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$': {
      id: '/media/$'
      path: '/media/$'
      fullPath: '/media/$'
      preLoaderRoute: typeof MediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/channels/': {
      id: '/_workspace/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof WorkspaceChannelsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/channels/$channelId': {
      id: '/_workspace/channels/$channelId'
      path: '/channels/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof WorkspaceChannelsChannelIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/projects/': {
      id: '/_workspace/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof WorkspaceProjectsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/projects/$projectId': {
      id: '/_workspace/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof WorkspaceProjectsProjectIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceLibraryRoute: typeof WorkspaceLibraryRoute
  WorkspaceRendersRoute: typeof WorkspaceRendersRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceChannelsChannelIdRoute: typeof WorkspaceChannelsChannelIdRoute
  WorkspaceProjectsProjectIdRoute: typeof WorkspaceProjectsProjectIdRoute
  WorkspaceChannelsIndexRoute: typeof WorkspaceChannelsIndexRoute
  WorkspaceProjectsIndexRoute: typeof WorkspaceProjectsIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceLibraryRoute: WorkspaceLibraryRoute,
  WorkspaceRendersRoute: WorkspaceRendersRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceChannelsChannelIdRoute: WorkspaceChannelsChannelIdRoute,
  WorkspaceProjectsProjectIdRoute: WorkspaceProjectsProjectIdRoute,
  WorkspaceChannelsIndexRoute: WorkspaceChannelsIndexRoute,
  WorkspaceProjectsIndexRoute: WorkspaceProjectsIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  RedocRoute: RedocRoute,
  ApiSplatRoute: ApiSplatRoute,
  DocsOauth2RedirectRoute: DocsOauth2RedirectRoute,
  McpSplatRoute: McpSplatRoute,
  MediaSplatRoute: MediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
